---
sidebar: modules
---

# Readings

For this module, choose one or more materials directly related to the module's topic. You may select materials from the course reading list or use relevant materials found elsewhere.

As a general guide, read one or more articles or other written materials totaling approximately 10,000–12,000 words, listen to or watch at least 90 minutes of podcasts or videos, or complete a comparable combination of written and audiovisual materials. You may engage with additional materials.

Please submit all graded work via Canvas. Participation requirements and grading details are provided in Canvas.

## Suggested Materials

- [How the machine 'thinks': Understanding opacity in machine learning algorithms](https://doi.org/10.1177/2053951715622512)
- [GeeksforGeeks: Machine Learning Tutorial](https://www.geeksforgeeks.org/machine-learning/machine-learning/)
- [AI & Machine Learning in Libraries](https://libereurope.github.io/ds-topic-guides/ai-ml.html)
- [Imagining library futures using AI and machine learning](https://hangingtogether.org/imagining-library-futures-using-ai-and-machine-learning/)
- [Underfitting and Overfitting in ML](https://www.geeksforgeeks.org/machine-learning/underfitting-and-overfitting-in-machine-learning/)
- 3Blue1Brown: But what is a neural network?
    <div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;">
    <iframe
        src="https://www.youtube-nocookie.com/embed/aircAruvnKk"
        title="But what is a neural network?"
        style="position:absolute;top:0;left:0;width:100%;height:100%;border:0;"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen>
    </iframe>
    </div>    
- [Google Machine Learning Education](https://developers.google.com/machine-learning):
    
    - [What is Machine Learning?](https://developers.google.com/machine-learning/intro-to-ml/what-is-ml)
    - [Supervised Learning](https://developers.google.com/machine-learning/intro-to-ml/supervised)
    - [Neural networks](https://developers.google.com/machine-learning/crash-course/neural-networks)

- [Neuro-symbolic approaches in artificial intelligence](https://doi.org/10.1093/nsr/nwac035)

