# Readings
- Martin Frické, [*Artificial Intelligence: Foundations of Computational Agents*](https://softoption.us/sites/default/files/AIinLibrariesNotesForTeaching3rdEd.pdf), Chapters 3, 8, 9
- Why Computer Vision Is a Hard Problem for AI
<div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;">
  <iframe
    src="https://www.youtube-nocookie.com/embed/YOKPo-I6cgs"
    title="Why Computer Vision Is a Hard Problem for AI"
    style="position:absolute;top:0;left:0;width:100%;height:100%;border:0;"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
    allowfullscreen>
  </iframe>
</div>

- [AI unlocks ancient Dead Sea Scrolls mystery](https://www.bbc.com/news/world-middle-east-56842712)
- [Digitizing the paper of record: Archiving digital newspapers at the New York Times](https://doi.org/10.1177/14648849211023849)
- [Managing the risks of inevitably biased visual artificial intelligence systems](https://www.brookings.edu/articles/managing-the-risks-of-inevitably-biased-visual-artificial-intelligence-systems/)
- [Computer Vision Tagging the Metropolitan Museum of Art's Collection: A Comparison of Three Systems](https://doi.org/10.1145/3446621)
- [Unmasking the bias in facial recognition algorithms](https://mitsloan.mit.edu/ideas-made-to-matter/unmasking-bias-facial-recognition-algorithms)
- Simplilearn: Natural Language Processing In 10 Minutes
<div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;">
  <iframe
    src="https://www.youtube-nocookie.com/embed/6I-Alfkr5K4"
    title="Natural Language Processing In 10 Minutes"
    style="position:absolute;top:0;left:0;width:100%;height:100%;border:0;"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
    allowfullscreen>
  </iframe>
</div>

- [GeeksforGeeks: Natural Language Processing (NLP) Tutorial](https://www.geeksforgeeks.org/nlp/natural-language-processing-nlp-tutorial/)
- [GeeksforGeeks: Named Entity Recognition](https://www.geeksforgeeks.org/nlp/named-entity-recognition/)
- [GeeksforGeeks: What is Sentiment Analysis?](https://www.geeksforgeeks.org/machine-learning/what-is-sentiment-analysis/)
- [HathiTrust - Text and data mining resources](https://hathitrust.atlassian.net/servicedesk/customer/portal/1/topic/dd359fbc-c095-4319-a223-353ebf0fd5b2)
- [HathiTrust - How to Use HathiTrust Data Resources](https://www.hathitrust.org/member-libraries/resources-for-librarians/data-resources/)
- [Text & Data Mining resources @ UK Library](https://libguides.uky.edu/dsd-services/text-data-mining)
- [Topic Modeling and Digital Humanities](https://journalofdigitalhumanities.org/2-1/topic-modeling-and-digital-humanities-by-david-m-blei/)
- [ProQuest's TDM Studio](https://proquest.libguides.com/tdmstudio/home)
- [Google - Recommendation systems overview](https://developers.google.com/machine-learning/recommendation/overview/types)
