# Readings

- [GeeksforGeeks: What are LLM Parameters?](https://www.geeksforgeeks.org/artificial-intelligence/what-are-llm-parameters/)
- [OpenAI: What are tokens and how to count them?](https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them)
- [IBM: What is a context window?](https://www.ibm.com/think/topics/context-window)
- [Datasets for large language models: a comprehensive survey](https://doi.org/10.1007/s10462-025-11403-7)
- You may explore [this visualization of an LLM workflow](https://bbycroft.net/llm). It includes many technical details, so reviewing it is optional. You may simply explore the visualization to get a general sense of how LLM components connect.
- Optional: [Jay Alammar: The Illustrated Transformer](https://jalammar.github.io/illustrated-transformer/) explains the transformer architecture in detail. Some parts may be technically challenging.
- [AI Demystified: Introduction to large language models](https://uit.stanford.edu/service/techtraining/ai-demystified/llm)
- [Andreas Stöffelbauer: How Large Language Models work? From zero to ChatGPT](https://medium.com/data-science-at-microsoft/how-large-language-models-work-91c362f5b78f)
- [MIT Sloan Management Review: How LLMs Work: Top 10 Executive-Level Questions](https://sloanreview.mit.edu/article/how-llms-work/)
- [Drexel University: Dragons' Guide to GAI](https://drexel.edu/teaching-and-learning/resources/teaching-tech/dragons-guide-to-gai)
- Blog posts about Measuring LLM Performance
    - [Data leakage is a major issue when measuring LLM performance](https://t-redactyl.io/posts/2025-12-29-data-leakage-llm-measurement/)
    - [What LLM benchmarks get wrong about measuring model performance](https://t-redactyl.io/posts/2026-01-19-llm-benchmarks-have-issues-with-validity/)
    - [Why the LMArena is a flawed approach to LLM evaluation](https://t-redactyl.io/posts/2026-02-09-why-the-lm-arena-is-vibes-based/)
- [Simon Willison: Understanding the recent criticism of the Chatbot Arena](https://simonwillison.net/2025/Apr/30/criticism-of-the-chatbot-arena/)
- [The Leaderboard Illusion](https://doi.org/10.48550/arXiv.2504.20879)
- [Wikipedia: Language model benchmark](https://en.wikipedia.org/wiki/Language_model_benchmark)
- [Meta’s benchmarks for its new AI models are a bit misleading](https://techcrunch.com/2025/04/06/metas-benchmarks-for-its-new-ai-models-are-a-bit-misleading/)
- [Evidently AI: 30 LLM evaluation benchmarks and how they work](https://www.evidentlyai.com/llm-guide/llm-benchmarks)
- [A Multimodal World](https://huggingface.co/learn/computer-vision-course/en/unit4/multimodal-models/a_multimodal_world)
- [GeeksforGeeks: Multimodal Large Language Models](https://www.geeksforgeeks.org/artificial-intelligence/multimodal-large-language-models/)
- [Google: What is agentic AI?](https://cloud.google.com/discover/what-is-agentic-ai)
- Explaining Agentic AI: The Good, the Bad & the Ugly
<div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;">
    <iframe
        src="https://www.youtube-nocookie.com/embed/Gvt4TwGpqOs"
        title="Explaining Agentic AI: The Good, the Bad & the Ugly"
        style="position:absolute;top:0;left:0;width:100%;height:100%;border:0;"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen>
    </iframe>
</div>
- [I asked ChatGPT if I should drive or walk to the car wash to get my car washed — and it struggled with basic logic](https://creators.yahoo.com/lifestyle/story/i-asked-chatgpt-if-i-should-drive-or-walk-to-the-car-wash-to-get-my-car-washed--and-it-struggled-with-basic-logic-140000959.html)

- [A Definition of AGI](https://doi.org/10.48550/arXiv.2510.18212)

- [Why language models hallucinate](https://openai.com/index/why-language-models-hallucinate/)
- [The AI revolution is running out of data. What can researchers do?](https://doi.org/10.1038/d41586-024-03990-2)
- [Anthropic: A small number of samples can poison LLMs of any size](https://www.anthropic.com/research/small-samples-poison)
- Yann LeCun: We Won't Reach AGI By Scaling Up LLMS
<div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;">
    <iframe
        src="https://www.youtube-nocookie.com/embed/4__gg83s_Do"
        title="Yann LeCun: We Won't Reach AGI By Scaling Up LLMS"
        style="position:absolute;top:0;left:0;width:100%;height:100%;border:0;"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen>
    </iframe>
</div>

- Richard Sutton – Father of RL thinks LLMs are a dead end
<div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;">
    <iframe
        src="https://www.youtube-nocookie.com/embed/21EYKqUsPfg"
        title="Richard Sutton – Father of RL thinks LLMs are a dead end"
        style="position:absolute;top:0;left:0;width:100%;height:100%;border:0;"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen>
    </iframe>
</div>

- How close is AGI? What the experts say.
<div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;">
    <iframe
        src="https://www.youtube-nocookie.com/embed/Z6q2iJZmvOM"
        title="How close is AGI? What the experts say."
        style="position:absolute;top:0;left:0;width:100%;height:100%;border:0;"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen>
    </iframe>
</div>

- Is AI Hiding Its Full Power? With Geoffrey Hinton
<div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;">
    <iframe
        src="https://www.youtube-nocookie.com/embed/l6ZcFa8pybE"
        title="Is AI Hiding Its Full Power? With Geoffrey Hinton"
        style="position:absolute;top:0;left:0;width:100%;height:100%;border:0;"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen>
    </iframe>
</div>