project:
  type: website
  output-dir: _site

website:
  title: "LIS/ICT 690 - AI Literacy for Information Organizations"
  site-url: "https://heng-zheng.github.io/ai-literacy/"
  page-navigation: true
  reader-mode: false
  navbar:
    background: "#0033A0"
    foreground: "#ffffff"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Modules"
        menu:
          - text: "Module 01"
            href: modules/intro-ai/intro-content.qmd
          - text: "Module 02"
            href: modules/search-discovery/search-content.qmd
          - text: "Module 03"
            href: modules/knowledge-systems/knowledge-content.qmd
          - text: "Module 04"
            href: modules/ai-society/society-content.qmd
          - text: "Module 05"
            href: modules/ai-concepts/concepts-content.qmd
          - text: "Module 06"
            href: modules/symbolic-ai/symbolic-content.qmd
          - text: "Module 07"
            href: modules/machine-learning/ml-content.qmd
          - text: "Module 08"
            href: modules/ml-applications/mla-content.qmd
          - text: "Module 09"
            href: modules/llms/llm-content.qmd
          - text: "Module 10"
            href: modules/prompting/prompt-content.qmd
          - text: "Module 11"
            href: modules/llm-tools/llmtool-content.qmd
          - text: "Module 12"
            href: modules/ai-concerns/concerns-content.qmd
          - text: "Module 13"
            href: modules/ai-governance/governance-content.qmd
          - text: "Module 14"
            href: modules/project-workshop/workshop-content.qmd
          - text: "Module 15"
            href: modules/final-project/fproject-content.qmd
      - text: "AI Watchlist"
        href: resources.qmd

format:
  html:
    theme:
      - cosmo
      - stylesheets/quarto-theme.scss
    css: stylesheets/quarto-extra.css
    toc: true
    toc-location: right
    code-copy: true
    link-external-newwindow: true
    anchor-sections: true
