# Module 12 Readings

- Business Insider: 
Exposing The Dark Side of America's AI Data Center Explosion
<div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;">
    <iframe
        src="https://www.youtube-nocookie.com/embed/t-8TDOFqkQA"
        title="Exposing The Dark Side of America's AI Data Center Explosion | View From Above | Business Insider"
        style="position:absolute;top:0;left:0;width:100%;height:100%;border:0;"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen>
    </iframe>
</div>

- Sims Witherspoon: Can AI Help Solve the Climate Crisis?
<div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;">
    <iframe
        src="https://www.youtube-nocookie.com/embed/RNhbqQefPSg"
        title="
Can AI Help Solve the Climate Crisis? | Sims Witherspoon | TED"
        style="position:absolute;top:0;left:0;width:100%;height:100%;border:0;"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen>
    </iframe>
</div>

- [Pew Research: What we know about energy use at U.S. data centers amid the AI boom](https://www.pewresearch.org/short-reads/2025/10/24/what-we-know-about-energy-use-at-us-data-centers-amid-the-ai-boom/)

- [Your Personal Information Is Probably Being Used to Train Generative AI Models](https://www.scientificamerican.com/article/your-personal-information-is-probably-being-used-to-train-generative-ai-models/)

- [Be Careful What You Tell Your AI Chatbot](https://hai.stanford.edu/news/be-careful-what-you-tell-your-ai-chatbot)

- [University of Kentucky: What to know about AI safety and Microsoft Copilot at UK](https://its.uky.edu/news/what-know-about-ai-safety-and-microsoft-copilot-uk)

- [Anthropic: Tracing the thoughts of a large language model](https://www.anthropic.com/research/tracing-thoughts-language-model)
- [OpenAI: Why language models hallucinate](https://openai.com/index/why-language-models-hallucinate/)
- [The Promethean Dilemma of AI at the Intersection of Hallucination and Creativity](https://cacm.acm.org/opinion/the-promethean-dilemma-of-ai-at-the-intersection-of-hallucination-and-creativity/)
- [New study warns of risks in AI chatbots giving medical advice](https://www.ox.ac.uk/news/2026-02-10-new-study-warns-risks-ai-chatbots-giving-medical-advice)

- [Anthropic Wins on Fair Use for Training its LLMs; Loses on Building a “Central Library” of Pirated Books](https://www.authorsalliance.org/2025/06/24/anthropic-wins-on-fair-use-for-training-its-llms-loses-on-building-a-central-library-of-pirated-books/)
- [Authors Guild on AI](https://authorsguild.org/advocacy/artificial-intelligence/)

- [Transparency in AI is on the Decline](https://hai.stanford.edu/news/transparency-in-ai-is-on-the-decline)

- [Artificial intelligence algorithm bias in information retrieval systems and its implication for library and information science professionals: A scoping review](https://doi.org/10.1080/07317131.2025.2512282)

- [How We Analyzed the COMPAS Recidivism Algorithm](https://www.propublica.org/article/how-we-analyzed-the-compas-recidivism-algorithm), also see the [dataset](https://www.kaggle.com/datasets/danofer/compass)

- [AI deskilling is a structural problem](https://doi.org/10.1007/s00146-025-02686-z)
- [The AI Deskilling Paradox](https://cacm.acm.org/news/the-ai-deskilling-paradox/)
- [AI's impacts on early career software engineers](https://spectrum.ieee.org/ai-effect-entry-level-jobs)
- [AI is Coming for Your Job. Now What? | Vlad Tenev | TED](https://www.youtube.com/watch?v=cJfKqKEyw1o)

- [Harvard Business School: Displacement or Complementarity? The Labor Market Impact of Generative AI](https://www.hbs.edu/faculty/Pages/download.aspx?name=25-039.pdf)
- [National Bureau of Economic Research: Artificial Intelligence and the Labor Market](http://doi.org/10.3386/w33509)
- [Anthropic: Labor market impacts of AI: A new measure and early evidence](https://www.anthropic.com/research/labor-market-impacts)

- [Uncovering inequalities in new knowledge learning by large language models across different languages](https://doi.org/10.1073/pnas.2514626122)
- [Nearly all Seoul students use generative AI](https://www.koreaherald.com/article/10652914)
- [Mind the (Language) Gap: Mapping the Challenges of LLM Development in Low-Resource Language Contexts](https://hai.stanford.edu/policy/mind-the-language-gap-mapping-the-challenges-of-llm-development-in-low-resource-language-contexts)

- [Rise of Concerns About AI: Reflections and Directions](https://cacm.acm.org/opinion/rise-of-concerns-about-ai/)
- [On the Dangers of Stochastic Parrots: Can Language Models Be Too Big?](https://doi.org/10.1145/3442188.3445922)
- [Teaching AI Ethics by Leon Furze](https://leonfurze.com/ai-ethics/)